### ISSUE TITLE
.gitignore file does not get published on npm

### ISSUE THREAD

**Issue by PranavBarthwal** [PranavBarthwal/backend-generator-cli#23]
.gitignore file inside the template folder does not get published on npm and hence when project is created using npm package does not have a .gitgnore file

**Comment by Aryan019** [comment]
The approach to solve this goes something like this - 
1. While packing in the packages changing the name of the .gitignore file to gitignore (so that the by default nature is not followed and the npm doesn't ignores it)

2. Renaming again to .gitignore at the time of just before publishing in the packages 

@PranavBarthwal Please assign this issue to me

**Comment by RNAdvani** [comment]
> .gitignore file inside the template folder does not get published on npm and hence when project is created using npm package does not have a .gitgnore file

check out the Pull requests
